services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: ecommerce
      MYSQL_DATABASE: ecommerce
    ports:
      - "33306:3306"
    volumes:
      - /Users/lee/Documents/개인공부/항해99/2주차/과제/docker/volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.2
    platform: linux/amd64
    container_name: ecommerce-redis
    ports:
      - "36379:6379"
    command: ["redis-server", "--requirepass", "ecommerce"]
